### ISSUE TITLE
Improving the website layout

### ISSUE THREAD

**Issue by jyim6** [jyim6/Neurally-Drawn#16]
The website is shaping up but I'm unsatisfied with the white space below the footer and the relative sizing of elements and their layout. We should make the layout dynamic to change with the size of the browser window where the footer goes all the way to the bottom, the nav bar and header change in size, and the picture viewer takes up all the space in the middle.

**Comment by jonmseaman** [comment]
I agree. I noticed the whitespace at the bottom, but I thought it was a good start. I will look into this.
