### ISSUE TITLE
Future site setup

### ISSUE THREAD

**Issue by jonmseaman** [jyim6/Neurally-Drawn#18]
It looks to me that the site should end up having these links on the nav panel:
* Home, the home page
* View, the image viewer. Where the uses views uploaded images, style images, and stylized images.
* Upload, where the user uploads their own pictures.
* Stylize, the 'neural artist' app. Where the user goes to stylize images.

Does this sound like a good set up?

**Comment by jyim6** [comment]
Yup sounds good to me. Of course in the future we're going to have to implement some way to manage different users.
