### ISSUE TITLE
Slow pictures page

### ISSUE THREAD

**Issue by jonmseaman** [jyim6/Neurally-Drawn#21]
Is the pictures page slow for you?

**Comment by jyim6** [comment]
You mean loading? It's pretty quick for me.

**Comment by jonmseaman** [comment]
Yes, loading is slow for me. I had 19 images in db. I deleted all but one and it seems faster, but still somewhat slow. The other pages are essentially instant.

**Comment by jonmseaman** [comment]
Is you admin site slow? The admin site is also slow for me.

**Comment by jyim6** [comment]
ah I only had two pictures in the db when I went on the website. No, admin site isn't slow but I still only have 2 pictures in the db.

**Comment by jonmseaman** [comment]
I'm guessing it is a problem on my end then.

**Comment by jonmseaman** [comment]
Is the view page at all slower than the other pages?

**Comment by jonmseaman** [comment]
I fixed my problem with performance. It required I change the settings.py 'HOST' to 127.0.0.1
