### ISSUE TITLE
App URL

### ISSUE THREAD

**Issue by jonmseaman** [jyim6/Neurally-Drawn#7]
It seems like it would be more convenient to have the picture_holder app root url located at the root of the website.
ie, localhost/upload/ instead of localhost/pictures/upload.

Thoughts?

**Comment by jyim6** [comment]
Ok i thought upload was a directory i had in my old version. Now I know what you mean. Picture_holder is just a app to hold the pictures. There's going to be another app for the neural network so we shouldn't have the root url located at the root. The root url should be a menu to access the different apps. Or maybe have them both on the same page in the future.

**Comment by jonmseaman** [comment]
One possibility is to have them both at root. Then we'd have /upload, /stylize, /whatever etc. I don't think any of the regexes will overlap from either app.

I guess the decision is between having the pictures app as the home page, or having a separate home page. To me, it seems better to have the pictures app as the home page because there are only going to be a few pages, and I think the user will want to access the pictures app first, then stylize.

**Comment by jyim6** [comment]
We could definitely make the pictures app the homepage but the user would want some sort of instruction and information about the app. I feel like that should be the homepage and the apps should be  reachable using the links on the left side.
