### ISSUE TITLE
Better Pages

### ISSUE THREAD

**Issue by jonmseaman** [jyim6/Neurally-Drawn#8]
Do you have a plan for the appearance of the site? I wanted to make it look a little nicer and add some links to make at least the homepage a little more functional.

**Comment by jyim6** [comment]
If you know any css then it would be great to make it look better. But this should be last after we get functionality.

**Comment by jonmseaman** [comment]
Alright. I think it would make the site easier and faster to test though, and only require minimal updating later.

Do you like this setup: http://www.w3schools.com/html/tryit.asp?filename=tryhtml_layout_semantic

**Comment by jyim6** [comment]
yeah I was looking at that. You should make something with that layout be the base.html. Th left side with links to the apps/other pages. The top should just have the app name but not as big as w3 has it.

**Comment by jonmseaman** [comment]
Yeah, it is a bit big.
I can work on it.
